# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName("mw")
        mw.resize(414, 421)
        self.centralwidget = QtWidgets.QWidget(mw)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(150, 150, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        mw.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        mw.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mw)
        self.statusbar.setObjectName("statusbar")
        mw.setStatusBar(self.statusbar)

        self.retranslateUi(mw)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        _translate = QtCore.QCoreApplication.translate
        mw.setWindowTitle(_translate("mw", "MainWindow"))
        self.btn.setText(_translate("mw", "Нарисовать"))
